name: Bug Report
description: Create a bug report to help us improve the code!
labels: ['bug', 'needs triage']
body:
    - type: textarea
      id: description
      attributes:
          label: Describe the bug
          description: A clear and concise description of what the bug is.
          placeholder: Describe the bug...
      validations:
          required: true
    - type: textarea
      id: reproduction
      attributes:
          label: Reproduction
          description: Steps to reproduce the behaviour
          placeholder: How does it happen?...
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Logs
          description: Please copy and paste the errors from console
          render: shell
    - type: textarea
      id: system-info
      attributes:
          label: System Info
          description: Output of `npx envinfo --system --binaries --npmPackages nitrado.js` within project directory.
          render: shell
          placeholder: System Information...
      validations:
          required: true
