name: 'Feature Request'
description: Request a new feature in Nitrado.js
labels: ['enhancement', 'needs triage']
body:
    - type: textarea
      id: related-issue
      attributes:
          label: Is your feature request related to a problem?
          description: Is there a issue currently open within issues.
          placeholder: I'm always frustrated with this issue...
      validations:
          required: false

    - type: textarea
      id: solution
      attributes:
          label: Describe the solution you'd like
          description: A clear and concise description of what you'd like to see in feature request.
          placeholder: I'd like to see this in the next version of Nitrado.js...
      validations:
          required: false

    - type: textarea
      id: alternatives
      attributes:
          label: Describe alternatives you've considered
          description: A description of what you've considered as alternatives to the solution you'd like to see in feature request.
          placeholder: I've considered the following alternatives...
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Any additional context you'd like to add to the feature request.
          placeholder: Add any other context or screenshots about the feature request here.
      validations:
          required: false
