# Theme
remote_theme: pmarsceill/just-the-docs
color_scheme: 'nitrado'

# Logo image
logo: '/assets/img/package-logo.png'

# Aux link in top right of page
aux_links:
    'Nitrado.js on GitHub':
        - 'https://github.com/cainthebest/nitrado.js'
# Aux link will open a new tab
aux_links_new_tab: true

# footer
footer_content: 'Copyright &copy; 2022 <a href="https://github.com/cainthebest">cainthebest</a>. Distributed under <a href="https://github.com/cainthebest/nitrado.js/blob/master/LICENSE.txt">GPL 3.0 license.</a>'
